name: PD Test
on:
  push:
    branches:
      - master
      - release-4.0
      - release-5.*
      - release-6.*
  pull_request:
    branches:
      - master
      - release-4.0
      - release-5.*
      - release-6.*
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  chunks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        worker_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    outputs:
      job-total: 10
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            **/.tools
            **/.dashboard_download_cache
          key: ${{ runner.os }}-go-${{ matrix.worker_id }}-${{ hashFiles('**/go.sum') }}
      - name: Make Test
        env:
          WORKER_ID: ${{ matrix.worker_id }}
          WORKER_COUNT: 10
        run: |
          [ $WORKER_ID -ne $WORKER_COUNT ] && make ci-test-job JOB_COUNT=$(($WORKER_COUNT-1)) JOB_INDEX=$WORKER_ID
          [ $WORKER_ID -eq $WORKER_COUNT ] && make ci-test-job-submod
          mv covprofile covprofile_$WORKER_ID
          sed -i "/failpoint_binding/d" covprofile_$WORKER_ID
      - name: Upload coverage result ${{ matrix.worker_id }}
        uses: actions/upload-artifact@v2
        with:
          name: cover-reports
          path: covprofile_${{ matrix.worker_id }}
  report-coverage:
    needs: chunks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download chunk report
        uses: actions/download-artifact@v2
        with:
          name: cover-reports
      - name: Merge
        env:
          TOTAL_JOBS: ${{needs.chunks.outputs.job-total}}
        run: for i in $(seq 1 $TOTAL_JOBS); do cat covprofile_$i >> covprofile; done
      - name: Send coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV }}
          file: ./covprofile
          flags: unittests
          name: codecov-umbrella
