name: TSO Consistency Test
on:
  # Only run when the new code is merged into master.
  push:
    branches:
      - master
jobs:
  tso-consistency-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make TSO Consistency Test
        run: make test-tso-consistency
